### ISSUE TITLE
Harbor Build Pipeline Broken

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#88] opened 2022-04-07 19:04 UTC
It looks like the harbor build pipeline is broken in the promotion stage. It appears it is because it is use a "v" in the version tag instead of proper semantic versioning. The eks-anywhere-test and eksa-packages repos could be used as examples for how it should be done. I'm not sure the exact problem

**Comment by vincentni** [comment] 2022-04-08 16:00
The root cause is the helm_promotion.sh doesn't fetch target registry and tag correctly. @jonahjon is working on a new solution for promotion and helm_promotion.sh will retire soon.

**Comment by TerryHowe** [comment] 2022-04-12 14:23
I guess Jonah is looking at this for now, job is working, but artifacts not promoted.

**Comment by jonahjon** [comment] 2022-04-22 16:27
This was presumably fixed by #101 doing some followup investigation.

**Comment by jonahjon** [comment] 2022-05-06 16:42
This looks fixed, closing issue.

**Closed by jonahjon** 2022-05-06 16:42 UTC
Labels: bug
